version: "3.7"
services:
    backend:
        container_name: backend
        build: trans-back/.
        ports:
            - 4000:4000
        volumes:
            - ./trans-back/src:/usr/src/app/src
