version: "3.7"
services:
    backend:
        container_name: backend
        build: back-end/
        ports:
            - 9696:4000
        volumes:
            - ./back-end/src:/usr/src/app/src
    frontend:
        container_name: frontend
        build: front-end/
        ports:
            - 6969:4000
        volumes:
            - ./front-end/src:/usr/src/app/src
        depends_on:
            - backend
