version: '3.7'
services:
  backend:
    container_name: backend
    build: back-end/
    ports:
      - 9696:4000
    volumes:
      - ./back-end/src:/usr/src/app/src
    depends_on:
      - db
    restart: always

  frontend:
    container_name: frontend
    build: front-end/
    ports:
      - 6969:4000
    volumes:
      - ./front-end/src:/usr/src/app/src
    depends_on:
      - backend

  db:
    container_name: db
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
